version: '3'
services:
    recipe-api:
        build: .
        image: recipe-api
        command: recipe-api-exe
        expose:
            - "8080"
    nginx:
        build: ./docker/nginx
        image: nginx
        ports:
            - "8080:80"
        depends_on:
            - recipe-api
